trigger:
- main

pool: 
 name: default
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'newactive'
    subscriptionId: 'b48d2576-2dcd-4086-8c4f-ffe54e0c0880'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Aakash'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'